2024-11-21 01:05:20,067 p=2462 u=vagrant n=ansible | [WARNING]: A duplicate localhost-like entry was found (localhost). First found localhost was 127.0.0.1

2024-11-21 01:05:20,384 p=2462 u=vagrant n=ansible | PLAY [testing,produccion] *****************************************************************************************************************************************************************************************************************************************************
2024-11-21 01:05:20,414 p=2462 u=vagrant n=ansible | TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
2024-11-21 01:05:20,593 p=2462 u=vagrant n=ansible | fatal: [127.0.0.1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '127.0.0.1' (ED25519) to the list of known hosts.\r\nvagrant@127.0.0.1: Permission denied (publickey,password).", "unreachable": true}
2024-11-21 01:05:21,694 p=2462 u=vagrant n=ansible | ok: [localhost]
2024-11-21 01:05:21,705 p=2462 u=vagrant n=ansible | TASK [include_role : TP_INI] **************************************************************************************************************************************************************************************************************************************************
2024-11-21 01:05:21,731 p=2462 u=vagrant n=ansible | TASK [TP_INI : Crear directorio] **********************************************************************************************************************************************************************************************************************************************
2024-11-21 01:05:21,980 p=2462 u=vagrant n=ansible | changed: [localhost]
2024-11-21 01:05:21,986 p=2462 u=vagrant n=ansible | TASK [TP_INI : Crear txt file] ************************************************************************************************************************************************************************************************************************************************
2024-11-21 01:05:22,126 p=2462 u=vagrant n=ansible | changed: [localhost]
2024-11-21 01:05:22,136 p=2462 u=vagrant n=ansible | TASK [Otra tarea] *************************************************************************************************************************************************************************************************************************************************************
2024-11-21 01:05:22,146 p=2462 u=vagrant n=ansible | ok: [localhost] => {
    "msg": "Despues de la ejecucion del rol"
}
2024-11-21 01:05:22,157 p=2462 u=vagrant n=ansible | PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
2024-11-21 01:05:22,158 p=2462 u=vagrant n=ansible | 127.0.0.1                  : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2024-11-21 01:05:22,159 p=2462 u=vagrant n=ansible | localhost                  : ok=4    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-11-21 01:38:21,890 p=3273 u=vagrant n=ansible | PLAY [testing,produccion] *****************************************************************************************************************************************************************************************************************************************************
2024-11-21 01:38:21,898 p=3273 u=vagrant n=ansible | TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
2024-11-21 01:38:23,277 p=3273 u=vagrant n=ansible | ok: [localhost]
2024-11-21 01:38:23,279 p=3273 u=vagrant n=ansible | ok: [vmHost2]
2024-11-21 01:38:23,290 p=3273 u=vagrant n=ansible | TASK [include_role : TP_INI] **************************************************************************************************************************************************************************************************************************************************
2024-11-21 01:38:23,333 p=3273 u=vagrant n=ansible | TASK [TP_INI : Crear directorio] **********************************************************************************************************************************************************************************************************************************************
2024-11-21 01:38:23,717 p=3273 u=vagrant n=ansible | ok: [vmHost2]
2024-11-21 01:38:23,720 p=3273 u=vagrant n=ansible | ok: [localhost]
2024-11-21 01:38:23,726 p=3273 u=vagrant n=ansible | TASK [TP_INI : Crear txt file] ************************************************************************************************************************************************************************************************************************************************
2024-11-21 01:38:24,021 p=3273 u=vagrant n=ansible | changed: [vmHost2]
2024-11-21 01:38:24,031 p=3273 u=vagrant n=ansible | changed: [localhost]
2024-11-21 01:38:24,039 p=3273 u=vagrant n=ansible | TASK [Otra tarea] *************************************************************************************************************************************************************************************************************************************************************
2024-11-21 01:38:24,066 p=3273 u=vagrant n=ansible | ok: [vmHost2] => {
    "msg": "Despues de la ejecucion del rol"
}
2024-11-21 01:38:24,069 p=3273 u=vagrant n=ansible | ok: [localhost] => {
    "msg": "Despues de la ejecucion del rol"
}
2024-11-21 01:38:24,080 p=3273 u=vagrant n=ansible | PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
2024-11-21 01:38:24,080 p=3273 u=vagrant n=ansible | localhost                  : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-11-21 01:38:24,080 p=3273 u=vagrant n=ansible | vmHost2                    : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-11-21 01:46:34,789 p=3634 u=vagrant n=ansible | PLAY [testing,produccion] *****************************************************************************************************************************************************************************************************************************************************
2024-11-21 01:46:34,796 p=3634 u=vagrant n=ansible | TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
2024-11-21 01:46:35,676 p=3634 u=vagrant n=ansible | ok: [localhost]
2024-11-21 01:46:38,078 p=3634 u=vagrant n=ansible | ok: [vmHost2]
2024-11-21 01:46:38,086 p=3634 u=vagrant n=ansible | TASK [include_role : TP_INI] **************************************************************************************************************************************************************************************************************************************************
2024-11-21 01:46:38,128 p=3634 u=vagrant n=ansible | TASK [TP_INI : Crear directorio] **********************************************************************************************************************************************************************************************************************************************
2024-11-21 01:46:38,428 p=3634 u=vagrant n=ansible | ok: [localhost]
2024-11-21 01:46:38,615 p=3634 u=vagrant n=ansible | changed: [vmHost2]
2024-11-21 01:46:38,621 p=3634 u=vagrant n=ansible | TASK [TP_INI : Crear txt file] ************************************************************************************************************************************************************************************************************************************************
2024-11-21 01:46:38,831 p=3634 u=vagrant n=ansible | changed: [localhost]
2024-11-21 01:46:39,093 p=3634 u=vagrant n=ansible | changed: [vmHost2]
2024-11-21 01:46:39,099 p=3634 u=vagrant n=ansible | TASK [Otra tarea] *************************************************************************************************************************************************************************************************************************************************************
2024-11-21 01:46:39,122 p=3634 u=vagrant n=ansible | ok: [vmHost2] => {
    "msg": "Despues de la ejecucion del rol"
}
2024-11-21 01:46:39,131 p=3634 u=vagrant n=ansible | ok: [localhost] => {
    "msg": "Despues de la ejecucion del rol"
}
2024-11-21 01:46:39,141 p=3634 u=vagrant n=ansible | PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
2024-11-21 01:46:39,142 p=3634 u=vagrant n=ansible | localhost                  : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-11-21 01:46:39,144 p=3634 u=vagrant n=ansible | vmHost2                    : ok=4    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-11-21 02:18:27,783 p=3930 u=vagrant n=ansible | PLAY [testing,produccion] *****************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:18:27,790 p=3930 u=vagrant n=ansible | TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:18:28,710 p=3930 u=vagrant n=ansible | ok: [localhost]
2024-11-21 02:18:29,120 p=3930 u=vagrant n=ansible | ok: [vmHost2]
2024-11-21 02:18:29,129 p=3930 u=vagrant n=ansible | TASK [include_role : TP_INI] **************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:18:29,170 p=3930 u=vagrant n=ansible | TASK [TP_INI : Crear directorio] **********************************************************************************************************************************************************************************************************************************************
2024-11-21 02:18:29,487 p=3930 u=vagrant n=ansible | ok: [localhost]
2024-11-21 02:18:29,673 p=3930 u=vagrant n=ansible | ok: [vmHost2]
2024-11-21 02:18:29,679 p=3930 u=vagrant n=ansible | TASK [TP_INI : Crear txt file] ************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:18:29,898 p=3930 u=vagrant n=ansible | changed: [localhost]
2024-11-21 02:18:30,141 p=3930 u=vagrant n=ansible | changed: [vmHost2]
2024-11-21 02:18:30,162 p=3930 u=vagrant n=ansible | TASK [TP_INI : template] ******************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:18:30,421 p=3930 u=vagrant n=ansible | fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'Variable_Vars_main' is undefined"}
2024-11-21 02:18:30,455 p=3930 u=vagrant n=ansible | fatal: [vmHost2]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'Variable_Vars_main' is undefined"}
2024-11-21 02:18:30,456 p=3930 u=vagrant n=ansible | PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:18:30,456 p=3930 u=vagrant n=ansible | localhost                  : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-21 02:18:30,457 p=3930 u=vagrant n=ansible | vmHost2                    : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-21 02:21:58,395 p=4213 u=vagrant n=ansible | PLAY [testing,produccion] *****************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:21:58,402 p=4213 u=vagrant n=ansible | TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:21:59,268 p=4213 u=vagrant n=ansible | ok: [localhost]
2024-11-21 02:21:59,664 p=4213 u=vagrant n=ansible | ok: [vmHost2]
2024-11-21 02:21:59,675 p=4213 u=vagrant n=ansible | TASK [include_role : TP_INI] **************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:21:59,716 p=4213 u=vagrant n=ansible | TASK [TP_INI : Crear directorio] **********************************************************************************************************************************************************************************************************************************************
2024-11-21 02:22:00,034 p=4213 u=vagrant n=ansible | ok: [localhost]
2024-11-21 02:22:00,238 p=4213 u=vagrant n=ansible | ok: [vmHost2]
2024-11-21 02:22:00,245 p=4213 u=vagrant n=ansible | TASK [TP_INI : Crear txt file] ************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:22:00,476 p=4213 u=vagrant n=ansible | changed: [localhost]
2024-11-21 02:22:00,752 p=4213 u=vagrant n=ansible | changed: [vmHost2]
2024-11-21 02:22:00,758 p=4213 u=vagrant n=ansible | TASK [TP_INI : template] ******************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:22:00,842 p=4213 u=vagrant n=ansible | fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'Variable_Vars_main' is undefined"}
2024-11-21 02:22:00,952 p=4213 u=vagrant n=ansible | fatal: [vmHost2]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'Variable_Vars_main' is undefined"}
2024-11-21 02:22:00,953 p=4213 u=vagrant n=ansible | PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:22:00,954 p=4213 u=vagrant n=ansible | localhost                  : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-21 02:22:00,954 p=4213 u=vagrant n=ansible | vmHost2                    : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-21 02:25:21,670 p=4459 u=vagrant n=ansible | PLAY [testing,produccion] *****************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:25:21,677 p=4459 u=vagrant n=ansible | TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:25:22,552 p=4459 u=vagrant n=ansible | ok: [localhost]
2024-11-21 02:25:22,947 p=4459 u=vagrant n=ansible | ok: [vmHost2]
2024-11-21 02:25:22,956 p=4459 u=vagrant n=ansible | TASK [include_role : TP_INI] **************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:25:22,996 p=4459 u=vagrant n=ansible | TASK [TP_INI : Crear directorio] **********************************************************************************************************************************************************************************************************************************************
2024-11-21 02:25:23,320 p=4459 u=vagrant n=ansible | ok: [localhost]
2024-11-21 02:25:23,522 p=4459 u=vagrant n=ansible | ok: [vmHost2]
2024-11-21 02:25:23,527 p=4459 u=vagrant n=ansible | TASK [TP_INI : Crear txt file] ************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:25:23,747 p=4459 u=vagrant n=ansible | changed: [localhost]
2024-11-21 02:25:23,995 p=4459 u=vagrant n=ansible | changed: [vmHost2]
2024-11-21 02:25:24,000 p=4459 u=vagrant n=ansible | TASK [TP_INI : template] ******************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:25:24,069 p=4459 u=vagrant n=ansible | fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'Variable_Vars_main' is undefined"}
2024-11-21 02:25:24,173 p=4459 u=vagrant n=ansible | fatal: [vmHost2]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'Variable_Vars_main' is undefined"}
2024-11-21 02:25:24,175 p=4459 u=vagrant n=ansible | PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:25:24,175 p=4459 u=vagrant n=ansible | localhost                  : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-21 02:25:24,176 p=4459 u=vagrant n=ansible | vmHost2                    : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-21 02:32:04,595 p=4707 u=vagrant n=ansible | PLAY [testing,produccion] *****************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:32:04,602 p=4707 u=vagrant n=ansible | TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:32:05,512 p=4707 u=vagrant n=ansible | ok: [localhost]
2024-11-21 02:32:05,888 p=4707 u=vagrant n=ansible | ok: [vmHost2]
2024-11-21 02:32:05,897 p=4707 u=vagrant n=ansible | TASK [include_role : TP_INI] **************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:32:05,933 p=4707 u=vagrant n=ansible | ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  mapping values are not allowed in this context

The error appears to be in '/home/vagrant/repogit/TP_AySO_Integral_Nuxez
/ansible/roles/TP_INI/tasks/main.yml': line 18, column 19, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

 - name: vars
      include_vars: ../vars/main.yml
                  ^ here

2024-11-21 02:32:05,935 p=4707 u=vagrant n=ansible | PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:32:05,935 p=4707 u=vagrant n=ansible | localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-11-21 02:32:05,935 p=4707 u=vagrant n=ansible | vmHost2                    : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-11-21 02:33:57,575 p=4864 u=vagrant n=ansible | PLAY [testing,produccion] *****************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:33:57,582 p=4864 u=vagrant n=ansible | TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:33:58,455 p=4864 u=vagrant n=ansible | ok: [localhost]
2024-11-21 02:33:58,824 p=4864 u=vagrant n=ansible | ok: [vmHost2]
2024-11-21 02:33:58,833 p=4864 u=vagrant n=ansible | TASK [include_role : TP_INI] **************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:33:58,871 p=4864 u=vagrant n=ansible | ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  mapping values are not allowed in this context

The error appears to be in '/home/vagrant/repogit/TP_AySO_Integral_Nuxez
/ansible/roles/TP_INI/tasks/main.yml': line 18, column 19, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

 - name: vars
      include_vars: "../vars/main.yml"
                  ^ here

2024-11-21 02:33:58,873 p=4864 u=vagrant n=ansible | PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:33:58,873 p=4864 u=vagrant n=ansible | localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-11-21 02:33:58,873 p=4864 u=vagrant n=ansible | vmHost2                    : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-11-21 02:39:49,998 p=4994 u=vagrant n=ansible | PLAY [testing,produccion] *****************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:39:50,005 p=4994 u=vagrant n=ansible | TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:39:50,900 p=4994 u=vagrant n=ansible | ok: [localhost]
2024-11-21 02:39:51,298 p=4994 u=vagrant n=ansible | ok: [vmHost2]
2024-11-21 02:39:51,308 p=4994 u=vagrant n=ansible | TASK [include_role : TP_INI] **************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:39:51,348 p=4994 u=vagrant n=ansible | TASK [TP_INI : Crear directorio] **********************************************************************************************************************************************************************************************************************************************
2024-11-21 02:39:51,676 p=4994 u=vagrant n=ansible | ok: [localhost]
2024-11-21 02:39:51,861 p=4994 u=vagrant n=ansible | ok: [vmHost2]
2024-11-21 02:39:51,866 p=4994 u=vagrant n=ansible | TASK [TP_INI : Crear txt file] ************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:39:52,073 p=4994 u=vagrant n=ansible | changed: [localhost]
2024-11-21 02:39:52,320 p=4994 u=vagrant n=ansible | changed: [vmHost2]
2024-11-21 02:39:52,326 p=4994 u=vagrant n=ansible | TASK [TP_INI : template] ******************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:39:52,400 p=4994 u=vagrant n=ansible | fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'Variable_Vars_main' is undefined"}
2024-11-21 02:39:52,501 p=4994 u=vagrant n=ansible | fatal: [vmHost2]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'Variable_Vars_main' is undefined"}
2024-11-21 02:39:52,502 p=4994 u=vagrant n=ansible | PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:39:52,502 p=4994 u=vagrant n=ansible | localhost                  : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-21 02:39:52,503 p=4994 u=vagrant n=ansible | vmHost2                    : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-21 02:42:51,610 p=5206 u=vagrant n=ansible | PLAY [testing,produccion] *****************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:42:51,617 p=5206 u=vagrant n=ansible | TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:42:52,487 p=5206 u=vagrant n=ansible | ok: [localhost]
2024-11-21 02:42:52,878 p=5206 u=vagrant n=ansible | ok: [vmHost2]
2024-11-21 02:42:52,888 p=5206 u=vagrant n=ansible | TASK [include_role : TP_INI] **************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:42:52,926 p=5206 u=vagrant n=ansible | TASK [TP_INI : Crear directorio] **********************************************************************************************************************************************************************************************************************************************
2024-11-21 02:42:53,252 p=5206 u=vagrant n=ansible | ok: [localhost]
2024-11-21 02:42:53,433 p=5206 u=vagrant n=ansible | ok: [vmHost2]
2024-11-21 02:42:53,439 p=5206 u=vagrant n=ansible | TASK [TP_INI : Crear txt file] ************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:42:53,652 p=5206 u=vagrant n=ansible | changed: [localhost]
2024-11-21 02:42:53,900 p=5206 u=vagrant n=ansible | changed: [vmHost2]
2024-11-21 02:42:53,908 p=5206 u=vagrant n=ansible | TASK [TP_INI : Crear txt con plantilla] ***************************************************************************************************************************************************************************************************************************************
2024-11-21 02:42:53,975 p=5206 u=vagrant n=ansible | fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'Variable_Vars_main' is undefined"}
2024-11-21 02:42:54,081 p=5206 u=vagrant n=ansible | fatal: [vmHost2]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'Variable_Vars_main' is undefined"}
2024-11-21 02:42:54,082 p=5206 u=vagrant n=ansible | PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:42:54,083 p=5206 u=vagrant n=ansible | localhost                  : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-21 02:42:54,083 p=5206 u=vagrant n=ansible | vmHost2                    : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-21 02:50:40,365 p=5581 u=vagrant n=ansible | PLAY [testing,produccion] *****************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:50:40,372 p=5581 u=vagrant n=ansible | TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:50:41,277 p=5581 u=vagrant n=ansible | ok: [localhost]
2024-11-21 02:50:41,662 p=5581 u=vagrant n=ansible | ok: [vmHost2]
2024-11-21 02:50:41,672 p=5581 u=vagrant n=ansible | TASK [include_role : TP_INI] **************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:50:41,712 p=5581 u=vagrant n=ansible | TASK [TP_INI : Crear directorio] **********************************************************************************************************************************************************************************************************************************************
2024-11-21 02:50:42,036 p=5581 u=vagrant n=ansible | ok: [localhost]
2024-11-21 02:50:42,235 p=5581 u=vagrant n=ansible | ok: [vmHost2]
2024-11-21 02:50:42,240 p=5581 u=vagrant n=ansible | TASK [TP_INI : Crear txt file] ************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:50:42,452 p=5581 u=vagrant n=ansible | changed: [localhost]
2024-11-21 02:50:42,702 p=5581 u=vagrant n=ansible | changed: [vmHost2]
2024-11-21 02:50:42,710 p=5581 u=vagrant n=ansible | TASK [TP_INI : Crear txt con plantilla] ***************************************************************************************************************************************************************************************************************************************
2024-11-21 02:50:42,786 p=5581 u=vagrant n=ansible | fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'Variable_Vars_main' is undefined"}
2024-11-21 02:50:42,878 p=5581 u=vagrant n=ansible | fatal: [vmHost2]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'Variable_Vars_main' is undefined"}
2024-11-21 02:50:42,882 p=5581 u=vagrant n=ansible | PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:50:42,882 p=5581 u=vagrant n=ansible | localhost                  : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-21 02:50:42,882 p=5581 u=vagrant n=ansible | vmHost2                    : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-21 02:52:56,773 p=5816 u=vagrant n=ansible | PLAY [testing,produccion] *****************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:52:56,781 p=5816 u=vagrant n=ansible | TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:52:57,643 p=5816 u=vagrant n=ansible | ok: [localhost]
2024-11-21 02:52:58,027 p=5816 u=vagrant n=ansible | ok: [vmHost2]
2024-11-21 02:52:58,036 p=5816 u=vagrant n=ansible | TASK [include_role : TP_INI] **************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:52:58,078 p=5816 u=vagrant n=ansible | TASK [TP_INI : Crear directorio] **********************************************************************************************************************************************************************************************************************************************
2024-11-21 02:52:58,393 p=5816 u=vagrant n=ansible | ok: [localhost]
2024-11-21 02:52:58,572 p=5816 u=vagrant n=ansible | ok: [vmHost2]
2024-11-21 02:52:58,578 p=5816 u=vagrant n=ansible | TASK [TP_INI : Crear txt file] ************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:52:58,796 p=5816 u=vagrant n=ansible | changed: [localhost]
2024-11-21 02:52:59,036 p=5816 u=vagrant n=ansible | changed: [vmHost2]
2024-11-21 02:52:59,041 p=5816 u=vagrant n=ansible | TASK [TP_INI : Crear txt con plantilla] ***************************************************************************************************************************************************************************************************************************************
2024-11-21 02:52:59,110 p=5816 u=vagrant n=ansible | fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'Variable_Vars_main' is undefined"}
2024-11-21 02:52:59,217 p=5816 u=vagrant n=ansible | fatal: [vmHost2]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'Variable_Vars_main' is undefined"}
2024-11-21 02:52:59,218 p=5816 u=vagrant n=ansible | PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:52:59,218 p=5816 u=vagrant n=ansible | localhost                  : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-21 02:52:59,219 p=5816 u=vagrant n=ansible | vmHost2                    : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-21 02:55:33,470 p=6033 u=vagrant n=ansible | PLAY [testing,produccion] *****************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:55:33,477 p=6033 u=vagrant n=ansible | TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:55:34,356 p=6033 u=vagrant n=ansible | ok: [localhost]
2024-11-21 02:55:34,741 p=6033 u=vagrant n=ansible | ok: [vmHost2]
2024-11-21 02:55:34,750 p=6033 u=vagrant n=ansible | TASK [include_role : TP_INI] **************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:55:34,792 p=6033 u=vagrant n=ansible | TASK [TP_INI : Crear directorio] **********************************************************************************************************************************************************************************************************************************************
2024-11-21 02:55:35,128 p=6033 u=vagrant n=ansible | ok: [localhost]
2024-11-21 02:55:35,311 p=6033 u=vagrant n=ansible | ok: [vmHost2]
2024-11-21 02:55:35,316 p=6033 u=vagrant n=ansible | TASK [TP_INI : Crear txt file] ************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:55:35,529 p=6033 u=vagrant n=ansible | changed: [localhost]
2024-11-21 02:55:35,776 p=6033 u=vagrant n=ansible | changed: [vmHost2]
2024-11-21 02:55:35,781 p=6033 u=vagrant n=ansible | TASK [TP_INI : Crear txt con plantilla] ***************************************************************************************************************************************************************************************************************************************
2024-11-21 02:55:35,848 p=6033 u=vagrant n=ansible | fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'Variable_Vars_main' is undefined"}
2024-11-21 02:55:35,952 p=6033 u=vagrant n=ansible | fatal: [vmHost2]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'Variable_Vars_main' is undefined"}
2024-11-21 02:55:35,953 p=6033 u=vagrant n=ansible | PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
2024-11-21 02:55:35,954 p=6033 u=vagrant n=ansible | localhost                  : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-21 02:55:35,954 p=6033 u=vagrant n=ansible | vmHost2                    : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-21 20:47:01,580 p=2538 u=vagrant n=ansible | PLAY [testing,produccion] *****************************************************************************************************************************************************************************************************************************************************
2024-11-21 20:47:01,625 p=2538 u=vagrant n=ansible | TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
2024-11-21 20:47:02,984 p=2538 u=vagrant n=ansible | ok: [localhost]
2024-11-21 20:47:05,025 p=2538 u=vagrant n=ansible | ok: [vmHost2]
2024-11-21 20:47:05,034 p=2538 u=vagrant n=ansible | TASK [include_role : TP_INI] **************************************************************************************************************************************************************************************************************************************************
2024-11-21 20:47:05,124 p=2538 u=vagrant n=ansible | TASK [TP_INI : Crear directorio] **********************************************************************************************************************************************************************************************************************************************
2024-11-21 20:47:05,491 p=2538 u=vagrant n=ansible | changed: [localhost]
2024-11-21 20:47:05,672 p=2538 u=vagrant n=ansible | ok: [vmHost2]
2024-11-21 20:47:05,677 p=2538 u=vagrant n=ansible | TASK [TP_INI : Crear txt file] ************************************************************************************************************************************************************************************************************************************************
2024-11-21 20:47:05,917 p=2538 u=vagrant n=ansible | changed: [localhost]
2024-11-21 20:47:06,151 p=2538 u=vagrant n=ansible | changed: [vmHost2]
2024-11-21 20:47:06,157 p=2538 u=vagrant n=ansible | TASK [TP_INI : Crear txt con plantilla] ***************************************************************************************************************************************************************************************************************************************
2024-11-21 20:47:06,293 p=2538 u=vagrant n=ansible | fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'Variable_Vars_main' is undefined"}
2024-11-21 20:47:06,332 p=2538 u=vagrant n=ansible | fatal: [vmHost2]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'Variable_Vars_main' is undefined"}
2024-11-21 20:47:06,334 p=2538 u=vagrant n=ansible | PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
2024-11-21 20:47:06,334 p=2538 u=vagrant n=ansible | localhost                  : ok=3    changed=2    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-21 20:47:06,334 p=2538 u=vagrant n=ansible | vmHost2                    : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-21 20:55:43,356 p=2797 u=vagrant n=ansible | PLAY [testing,produccion] *****************************************************************************************************************************************************************************************************************************************************
2024-11-21 20:55:43,364 p=2797 u=vagrant n=ansible | TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
2024-11-21 20:55:44,244 p=2797 u=vagrant n=ansible | ok: [localhost]
2024-11-21 20:55:44,757 p=2797 u=vagrant n=ansible | ok: [vmHost2]
2024-11-21 20:55:44,765 p=2797 u=vagrant n=ansible | TASK [include_role : TP_INI] **************************************************************************************************************************************************************************************************************************************************
2024-11-21 20:55:44,804 p=2797 u=vagrant n=ansible | TASK [TP_INI : Crear directorio] **********************************************************************************************************************************************************************************************************************************************
2024-11-21 20:55:45,110 p=2797 u=vagrant n=ansible | ok: [localhost]
2024-11-21 20:55:45,291 p=2797 u=vagrant n=ansible | ok: [vmHost2]
2024-11-21 20:55:45,296 p=2797 u=vagrant n=ansible | TASK [TP_INI : Crear txt file] ************************************************************************************************************************************************************************************************************************************************
2024-11-21 20:55:45,506 p=2797 u=vagrant n=ansible | changed: [localhost]
2024-11-21 20:55:45,748 p=2797 u=vagrant n=ansible | changed: [vmHost2]
2024-11-21 20:55:45,753 p=2797 u=vagrant n=ansible | TASK [TP_INI : Crear txt con plantilla] ***************************************************************************************************************************************************************************************************************************************
2024-11-21 20:55:46,446 p=2797 u=vagrant n=ansible | changed: [localhost]
2024-11-21 20:55:46,716 p=2797 u=vagrant n=ansible | changed: [vmHost2]
2024-11-21 20:55:46,722 p=2797 u=vagrant n=ansible | TASK [Otra tarea] *************************************************************************************************************************************************************************************************************************************************************
2024-11-21 20:55:46,749 p=2797 u=vagrant n=ansible | ok: [vmHost2] => {
    "msg": "Despues de la ejecucion del rol"
}
2024-11-21 20:55:46,752 p=2797 u=vagrant n=ansible | ok: [localhost] => {
    "msg": "Despues de la ejecucion del rol"
}
2024-11-21 20:55:46,763 p=2797 u=vagrant n=ansible | PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
2024-11-21 20:55:46,763 p=2797 u=vagrant n=ansible | localhost                  : ok=5    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-11-21 20:55:46,763 p=2797 u=vagrant n=ansible | vmHost2                    : ok=5    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-11-21 23:17:56,937 p=3202 u=vagrant n=ansible | [WARNING]: While constructing a mapping from /home/vagrant/repogit/TP_AySO_Integral_Nuxez
/ansible/playbook.yml, line 13, column 9, found a duplicate dict key (name). Using last defined value only.

2024-11-21 23:17:56,964 p=3202 u=vagrant n=ansible | PLAY [testing,produccion] *****************************************************************************************************************************************************************************************************************************************************
2024-11-21 23:17:56,972 p=3202 u=vagrant n=ansible | TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
2024-11-21 23:17:57,950 p=3202 u=vagrant n=ansible | ok: [localhost]
2024-11-21 23:17:58,466 p=3202 u=vagrant n=ansible | ok: [vmHost2]
2024-11-21 23:17:58,476 p=3202 u=vagrant n=ansible | TASK [include_role : /Alta_Usuarios_Nuxez
] *******************************************************************************************************************************************************************************************************************************
2024-11-21 23:17:58,511 p=3202 u=vagrant n=ansible | ERROR! the role '/Alta_Usuarios_Nuxez
' was not found in /home/vagrant/repogit/TP_AySO_Integral_Nuxez
/ansible/roles:/tmp:/home/vagrant/repogit/TP_AySO_Integral_Nuxez
:/home/vagrant/repogit/TP_AySO_Integral_Nuxez
/ansible

The error appears to be in '/home/vagrant/repogit/TP_AySO_Integral_Nuxez
/ansible/playbook.yml': line 14, column 15, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

        name: TP_INI
        name: /Alta_Usuarios_Nuxez

              ^ here

2024-11-21 23:17:58,512 p=3202 u=vagrant n=ansible | PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
2024-11-21 23:17:58,513 p=3202 u=vagrant n=ansible | localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-11-21 23:17:58,513 p=3202 u=vagrant n=ansible | vmHost2                    : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-11-21 23:18:27,279 p=3313 u=vagrant n=ansible | [WARNING]: While constructing a mapping from /home/vagrant/repogit/TP_AySO_Integral_Nuxez
/ansible/playbook.yml, line 13, column 9, found a duplicate dict key (name). Using last defined value only.

2024-11-21 23:18:27,302 p=3313 u=vagrant n=ansible | PLAY [testing,produccion] *****************************************************************************************************************************************************************************************************************************************************
2024-11-21 23:18:27,309 p=3313 u=vagrant n=ansible | TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
2024-11-21 23:18:28,193 p=3313 u=vagrant n=ansible | ok: [localhost]
2024-11-21 23:18:28,527 p=3313 u=vagrant n=ansible | ok: [vmHost2]
2024-11-21 23:18:28,536 p=3313 u=vagrant n=ansible | TASK [include_role : Alta_Usuarios_Nuxez
] ********************************************************************************************************************************************************************************************************************************
2024-11-21 23:18:28,576 p=3313 u=vagrant n=ansible | TASK [Alta_Usuarios_Nuxez
 : Crear Grupos] ********************************************************************************************************************************************************************************************************************************
2024-11-21 23:18:29,030 p=3313 u=vagrant n=ansible | failed: [localhost] (item=G_R1) => {"ansible_loop_var": "item", "changed": false, "item": "G_R1", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R1"}
2024-11-21 23:18:29,182 p=3313 u=vagrant n=ansible | failed: [localhost] (item=G_R2) => {"ansible_loop_var": "item", "changed": false, "item": "G_R2", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R2"}
2024-11-21 23:18:29,224 p=3313 u=vagrant n=ansible | failed: [vmHost2] (item=G_R1) => {"ansible_loop_var": "item", "changed": false, "item": "G_R1", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R1"}
2024-11-21 23:18:29,367 p=3313 u=vagrant n=ansible | failed: [localhost] (item=G_R3) => {"ansible_loop_var": "item", "changed": false, "item": "G_R3", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R3"}
2024-11-21 23:18:29,539 p=3313 u=vagrant n=ansible | failed: [localhost] (item=G_R4) => {"ansible_loop_var": "item", "changed": false, "item": "G_R4", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R4"}
2024-11-21 23:18:29,710 p=3313 u=vagrant n=ansible | failed: [localhost] (item=G_R5) => {"ansible_loop_var": "item", "changed": false, "item": "G_R5", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R5"}
2024-11-21 23:18:29,724 p=3313 u=vagrant n=ansible | failed: [vmHost2] (item=G_R2) => {"ansible_loop_var": "item", "changed": false, "item": "G_R2", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R2"}
2024-11-21 23:18:29,922 p=3313 u=vagrant n=ansible | failed: [localhost] (item=G_R6) => {"ansible_loop_var": "item", "changed": false, "item": "G_R6", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R6"}
2024-11-21 23:18:30,170 p=3313 u=vagrant n=ansible | failed: [vmHost2] (item=G_R3) => {"ansible_loop_var": "item", "changed": false, "item": "G_R3", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R3"}
2024-11-21 23:18:30,581 p=3313 u=vagrant n=ansible | failed: [vmHost2] (item=G_R4) => {"ansible_loop_var": "item", "changed": false, "item": "G_R4", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R4"}
2024-11-21 23:18:31,001 p=3313 u=vagrant n=ansible | failed: [vmHost2] (item=G_R5) => {"ansible_loop_var": "item", "changed": false, "item": "G_R5", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R5"}
2024-11-21 23:18:31,400 p=3313 u=vagrant n=ansible | failed: [vmHost2] (item=G_R6) => {"ansible_loop_var": "item", "changed": false, "item": "G_R6", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R6"}
2024-11-21 23:18:31,401 p=3313 u=vagrant n=ansible | PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
2024-11-21 23:18:31,402 p=3313 u=vagrant n=ansible | localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-21 23:18:31,402 p=3313 u=vagrant n=ansible | vmHost2                    : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-21 23:33:33,847 p=3634 u=vagrant n=ansible | [WARNING]: While constructing a mapping from /home/vagrant/repogit/TP_AySO_Integral_Nuxez
/ansible/playbook.yml, line 13, column 9, found a duplicate dict key (name). Using last defined value only.

2024-11-21 23:33:33,869 p=3634 u=vagrant n=ansible | PLAY [testing,produccion] *****************************************************************************************************************************************************************************************************************************************************
2024-11-21 23:33:33,877 p=3634 u=vagrant n=ansible | TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
2024-11-21 23:33:34,736 p=3634 u=vagrant n=ansible | ok: [localhost]
2024-11-21 23:33:35,288 p=3634 u=vagrant n=ansible | ok: [vmHost2]
2024-11-21 23:33:35,298 p=3634 u=vagrant n=ansible | TASK [include_role : Alta_Usuarios_Nuxez
] ********************************************************************************************************************************************************************************************************************************
2024-11-21 23:33:35,337 p=3634 u=vagrant n=ansible | TASK [Alta_Usuarios_Nuxez
 : Crear Grupos] ********************************************************************************************************************************************************************************************************************************
2024-11-21 23:33:35,672 p=3634 u=vagrant n=ansible | failed: [localhost] (item=G_R1) => {"ansible_loop_var": "item", "changed": false, "item": "G_R1", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R1"}
2024-11-21 23:33:35,828 p=3634 u=vagrant n=ansible | failed: [localhost] (item=G_R2) => {"ansible_loop_var": "item", "changed": false, "item": "G_R2", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R2"}
2024-11-21 23:33:35,878 p=3634 u=vagrant n=ansible | failed: [vmHost2] (item=G_R1) => {"ansible_loop_var": "item", "changed": false, "item": "G_R1", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R1"}
2024-11-21 23:33:36,010 p=3634 u=vagrant n=ansible | failed: [localhost] (item=G_R3) => {"ansible_loop_var": "item", "changed": false, "item": "G_R3", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R3"}
2024-11-21 23:33:36,179 p=3634 u=vagrant n=ansible | failed: [localhost] (item=G_R4) => {"ansible_loop_var": "item", "changed": false, "item": "G_R4", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R4"}
2024-11-21 23:33:36,332 p=3634 u=vagrant n=ansible | failed: [localhost] (item=G_R5) => {"ansible_loop_var": "item", "changed": false, "item": "G_R5", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R5"}
2024-11-21 23:33:36,369 p=3634 u=vagrant n=ansible | failed: [vmHost2] (item=G_R2) => {"ansible_loop_var": "item", "changed": false, "item": "G_R2", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R2"}
2024-11-21 23:33:36,514 p=3634 u=vagrant n=ansible | failed: [localhost] (item=G_R6) => {"ansible_loop_var": "item", "changed": false, "item": "G_R6", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R6"}
2024-11-21 23:33:36,798 p=3634 u=vagrant n=ansible | failed: [vmHost2] (item=G_R3) => {"ansible_loop_var": "item", "changed": false, "item": "G_R3", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R3"}
2024-11-21 23:33:37,196 p=3634 u=vagrant n=ansible | failed: [vmHost2] (item=G_R4) => {"ansible_loop_var": "item", "changed": false, "item": "G_R4", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R4"}
2024-11-21 23:33:37,598 p=3634 u=vagrant n=ansible | failed: [vmHost2] (item=G_R5) => {"ansible_loop_var": "item", "changed": false, "item": "G_R5", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R5"}
2024-11-21 23:33:37,997 p=3634 u=vagrant n=ansible | failed: [vmHost2] (item=G_R6) => {"ansible_loop_var": "item", "changed": false, "item": "G_R6", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R6"}
2024-11-21 23:33:37,999 p=3634 u=vagrant n=ansible | PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
2024-11-21 23:33:37,999 p=3634 u=vagrant n=ansible | localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-21 23:33:37,999 p=3634 u=vagrant n=ansible | vmHost2                    : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-21 23:37:08,813 p=4101 u=vagrant n=ansible | [WARNING]: While constructing a mapping from /home/vagrant/repogit/TP_AySO_Integral_Nuxez
/ansible/playbook.yml, line 13, column 9, found a duplicate dict key (name). Using last defined value only.

2024-11-21 23:37:08,836 p=4101 u=vagrant n=ansible | PLAY [testing,produccion] *****************************************************************************************************************************************************************************************************************************************************
2024-11-21 23:37:08,845 p=4101 u=vagrant n=ansible | TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
2024-11-21 23:37:09,716 p=4101 u=vagrant n=ansible | ok: [localhost]
2024-11-21 23:37:10,249 p=4101 u=vagrant n=ansible | ok: [vmHost2]
2024-11-21 23:37:10,259 p=4101 u=vagrant n=ansible | TASK [include_role : Alta_Usuarios_Nuxez
] ********************************************************************************************************************************************************************************************************************************
2024-11-21 23:37:10,301 p=4101 u=vagrant n=ansible | TASK [Alta_Usuarios_Nuxez
 : Crear Grupos] ********************************************************************************************************************************************************************************************************************************
2024-11-21 23:37:10,647 p=4101 u=vagrant n=ansible | failed: [localhost] (item=G_R1) => {"ansible_loop_var": "item", "changed": false, "item": "G_R1", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R1"}
2024-11-21 23:37:10,810 p=4101 u=vagrant n=ansible | failed: [localhost] (item=G_R2) => {"ansible_loop_var": "item", "changed": false, "item": "G_R2", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R2"}
2024-11-21 23:37:10,862 p=4101 u=vagrant n=ansible | failed: [vmHost2] (item=G_R1) => {"ansible_loop_var": "item", "changed": false, "item": "G_R1", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R1"}
2024-11-21 23:37:10,999 p=4101 u=vagrant n=ansible | failed: [localhost] (item=G_R3) => {"ansible_loop_var": "item", "changed": false, "item": "G_R3", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R3"}
2024-11-21 23:37:11,174 p=4101 u=vagrant n=ansible | failed: [localhost] (item=G_R4) => {"ansible_loop_var": "item", "changed": false, "item": "G_R4", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R4"}
2024-11-21 23:37:11,337 p=4101 u=vagrant n=ansible | failed: [vmHost2] (item=G_R2) => {"ansible_loop_var": "item", "changed": false, "item": "G_R2", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R2"}
2024-11-21 23:37:11,347 p=4101 u=vagrant n=ansible | failed: [localhost] (item=G_R5) => {"ansible_loop_var": "item", "changed": false, "item": "G_R5", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R5"}
2024-11-21 23:37:11,534 p=4101 u=vagrant n=ansible | failed: [localhost] (item=G_R6) => {"ansible_loop_var": "item", "changed": false, "item": "G_R6", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R6"}
2024-11-21 23:37:11,784 p=4101 u=vagrant n=ansible | failed: [vmHost2] (item=G_R3) => {"ansible_loop_var": "item", "changed": false, "item": "G_R3", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R3"}
2024-11-21 23:37:12,182 p=4101 u=vagrant n=ansible | failed: [vmHost2] (item=G_R4) => {"ansible_loop_var": "item", "changed": false, "item": "G_R4", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R4"}
2024-11-21 23:37:12,578 p=4101 u=vagrant n=ansible | failed: [vmHost2] (item=G_R5) => {"ansible_loop_var": "item", "changed": false, "item": "G_R5", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R5"}
2024-11-21 23:37:12,972 p=4101 u=vagrant n=ansible | failed: [vmHost2] (item=G_R6) => {"ansible_loop_var": "item", "changed": false, "item": "G_R6", "msg": "groupadd: Permission denied.\ngroupadd: cannot lock /etc/group; try again later.\n", "name": "G_R6"}
2024-11-21 23:37:12,973 p=4101 u=vagrant n=ansible | PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
2024-11-21 23:37:12,973 p=4101 u=vagrant n=ansible | localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-21 23:37:12,974 p=4101 u=vagrant n=ansible | vmHost2                    : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-21 23:39:51,848 p=4423 u=vagrant n=ansible | [WARNING]: While constructing a mapping from /home/vagrant/repogit/TP_AySO_Integral_Nuxez
/ansible/playbook.yml, line 13, column 9, found a duplicate dict key (name). Using last defined value only.

2024-11-21 23:39:51,871 p=4423 u=vagrant n=ansible | PLAY [testing,produccion] *****************************************************************************************************************************************************************************************************************************************************
2024-11-21 23:39:51,880 p=4423 u=vagrant n=ansible | TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
2024-11-21 23:39:52,743 p=4423 u=vagrant n=ansible | ok: [localhost]
2024-11-21 23:39:53,284 p=4423 u=vagrant n=ansible | ok: [vmHost2]
2024-11-21 23:39:53,292 p=4423 u=vagrant n=ansible | TASK [include_role : Alta_Usuarios_Nuxez
] ********************************************************************************************************************************************************************************************************************************
2024-11-21 23:39:53,333 p=4423 u=vagrant n=ansible | TASK [Alta_Usuarios_Nuxez
 : Crear Grupos] ********************************************************************************************************************************************************************************************************************************
2024-11-21 23:39:53,669 p=4423 u=vagrant n=ansible | failed: [localhost] (item=G_R1) => {"ansible_loop_var": "item", "changed": false, "item": "G_R1", "msg": "Unsupported parameters for (ansible.builtin.group) module: become Supported parameters include: gid, local, name, non_unique, state, system"}
2024-11-21 23:39:53,825 p=4423 u=vagrant n=ansible | failed: [localhost] (item=G_R2) => {"ansible_loop_var": "item", "changed": false, "item": "G_R2", "msg": "Unsupported parameters for (ansible.builtin.group) module: become Supported parameters include: gid, local, name, non_unique, state, system"}
2024-11-21 23:39:53,890 p=4423 u=vagrant n=ansible | failed: [vmHost2] (item=G_R1) => {"ansible_loop_var": "item", "changed": false, "item": "G_R1", "msg": "Unsupported parameters for (ansible.builtin.group) module: become Supported parameters include: gid, local, name, non_unique, state, system"}
2024-11-21 23:39:54,020 p=4423 u=vagrant n=ansible | failed: [localhost] (item=G_R3) => {"ansible_loop_var": "item", "changed": false, "item": "G_R3", "msg": "Unsupported parameters for (ansible.builtin.group) module: become Supported parameters include: gid, local, name, non_unique, state, system"}
2024-11-21 23:39:54,203 p=4423 u=vagrant n=ansible | failed: [localhost] (item=G_R4) => {"ansible_loop_var": "item", "changed": false, "item": "G_R4", "msg": "Unsupported parameters for (ansible.builtin.group) module: become Supported parameters include: gid, local, name, non_unique, state, system"}
2024-11-21 23:39:54,356 p=4423 u=vagrant n=ansible | failed: [localhost] (item=G_R5) => {"ansible_loop_var": "item", "changed": false, "item": "G_R5", "msg": "Unsupported parameters for (ansible.builtin.group) module: become Supported parameters include: gid, local, name, non_unique, state, system"}
2024-11-21 23:39:54,369 p=4423 u=vagrant n=ansible | failed: [vmHost2] (item=G_R2) => {"ansible_loop_var": "item", "changed": false, "item": "G_R2", "msg": "Unsupported parameters for (ansible.builtin.group) module: become Supported parameters include: gid, local, name, non_unique, state, system"}
2024-11-21 23:39:54,540 p=4423 u=vagrant n=ansible | failed: [localhost] (item=G_R6) => {"ansible_loop_var": "item", "changed": false, "item": "G_R6", "msg": "Unsupported parameters for (ansible.builtin.group) module: become Supported parameters include: gid, local, name, non_unique, state, system"}
2024-11-21 23:39:54,806 p=4423 u=vagrant n=ansible | failed: [vmHost2] (item=G_R3) => {"ansible_loop_var": "item", "changed": false, "item": "G_R3", "msg": "Unsupported parameters for (ansible.builtin.group) module: become Supported parameters include: gid, local, name, non_unique, state, system"}
2024-11-21 23:39:55,219 p=4423 u=vagrant n=ansible | failed: [vmHost2] (item=G_R4) => {"ansible_loop_var": "item", "changed": false, "item": "G_R4", "msg": "Unsupported parameters for (ansible.builtin.group) module: become Supported parameters include: gid, local, name, non_unique, state, system"}
2024-11-21 23:39:55,606 p=4423 u=vagrant n=ansible | failed: [vmHost2] (item=G_R5) => {"ansible_loop_var": "item", "changed": false, "item": "G_R5", "msg": "Unsupported parameters for (ansible.builtin.group) module: become Supported parameters include: gid, local, name, non_unique, state, system"}
2024-11-21 23:39:55,996 p=4423 u=vagrant n=ansible | failed: [vmHost2] (item=G_R6) => {"ansible_loop_var": "item", "changed": false, "item": "G_R6", "msg": "Unsupported parameters for (ansible.builtin.group) module: become Supported parameters include: gid, local, name, non_unique, state, system"}
2024-11-21 23:39:56,000 p=4423 u=vagrant n=ansible | PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
2024-11-21 23:39:56,000 p=4423 u=vagrant n=ansible | localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-21 23:39:56,000 p=4423 u=vagrant n=ansible | vmHost2                    : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-21 23:58:24,805 p=4734 u=vagrant n=ansible | [WARNING]: While constructing a mapping from /home/vagrant/repogit/TP_AySO_Integral_Nuxez
/ansible/playbook.yml, line 13, column 9, found a duplicate dict key (name). Using last defined value only.

2024-11-21 23:58:24,828 p=4734 u=vagrant n=ansible | PLAY [testing,produccion] *****************************************************************************************************************************************************************************************************************************************************
2024-11-21 23:58:24,836 p=4734 u=vagrant n=ansible | TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
2024-11-21 23:58:25,724 p=4734 u=vagrant n=ansible | ok: [localhost]
2024-11-21 23:58:26,222 p=4734 u=vagrant n=ansible | ok: [vmHost2]
2024-11-21 23:58:26,231 p=4734 u=vagrant n=ansible | TASK [include_role : Alta_Usuarios_Nuxez
] ********************************************************************************************************************************************************************************************************************************
2024-11-21 23:58:26,272 p=4734 u=vagrant n=ansible | TASK [Alta_Usuarios_Nuxez
 : Crear Grupos] ********************************************************************************************************************************************************************************************************************************
2024-11-21 23:58:26,630 p=4734 u=vagrant n=ansible | changed: [localhost] => (item=G_R1)
2024-11-21 23:58:26,796 p=4734 u=vagrant n=ansible | changed: [localhost] => (item=G_R2)
2024-11-21 23:58:26,959 p=4734 u=vagrant n=ansible | changed: [localhost] => (item=G_R3)
2024-11-21 23:58:27,121 p=4734 u=vagrant n=ansible | changed: [localhost] => (item=G_R4)
2024-11-21 23:58:27,292 p=4734 u=vagrant n=ansible | changed: [vmHost2] => (item=G_R1)
2024-11-21 23:58:27,311 p=4734 u=vagrant n=ansible | changed: [localhost] => (item=G_R5)
2024-11-21 23:58:27,524 p=4734 u=vagrant n=ansible | changed: [localhost] => (item=G_R6)
2024-11-21 23:58:27,813 p=4734 u=vagrant n=ansible | changed: [vmHost2] => (item=G_R2)
2024-11-21 23:58:28,268 p=4734 u=vagrant n=ansible | changed: [vmHost2] => (item=G_R3)
2024-11-21 23:58:28,732 p=4734 u=vagrant n=ansible | changed: [vmHost2] => (item=G_R4)
2024-11-21 23:58:29,187 p=4734 u=vagrant n=ansible | changed: [vmHost2] => (item=G_R5)
2024-11-21 23:58:29,651 p=4734 u=vagrant n=ansible | changed: [vmHost2] => (item=G_R6)
2024-11-21 23:58:29,657 p=4734 u=vagrant n=ansible | TASK [Alta_Usuarios_Nuxez
 : Crear usuarios y asignarlos a grupos] ********************************************************************************************************************************************************************************************************
2024-11-21 23:58:30,163 p=4734 u=vagrant n=ansible | changed: [localhost] => (item={'name': 'R1_Nuxez', 'groups': 'G_R1'})
2024-11-21 23:58:30,364 p=4734 u=vagrant n=ansible | changed: [localhost] => (item={'name': 'R2_Nuxez', 'groups': 'G_R3'})
2024-11-21 23:58:30,556 p=4734 u=vagrant n=ansible | changed: [vmHost2] => (item={'name': 'R1_Nuxez', 'groups': 'G_R1'})
2024-11-21 23:58:30,591 p=4734 u=vagrant n=ansible | changed: [localhost] => (item={'name': 'R3_Nuxez', 'groups': 'G_R4'})
2024-11-21 23:58:30,848 p=4734 u=vagrant n=ansible | changed: [localhost] => (item={'name': 'R4_Nuxez', 'groups': 'G_R4'})
2024-11-21 23:58:31,052 p=4734 u=vagrant n=ansible | changed: [localhost] => (item={'name': 'R5_Nuxez', 'groups': 'G_R5'})
2024-11-21 23:58:31,200 p=4734 u=vagrant n=ansible | changed: [vmHost2] => (item={'name': 'R2_Nuxez', 'groups': 'G_R3'})
2024-11-21 23:58:31,303 p=4734 u=vagrant n=ansible | changed: [localhost] => (item={'name': 'R6_Nuxez', 'groups': 'G_R6'})
2024-11-21 23:58:31,797 p=4734 u=vagrant n=ansible | changed: [vmHost2] => (item={'name': 'R3_Nuxez', 'groups': 'G_R4'})
2024-11-21 23:58:32,373 p=4734 u=vagrant n=ansible | changed: [vmHost2] => (item={'name': 'R4_Nuxez', 'groups': 'G_R4'})
2024-11-21 23:58:32,899 p=4734 u=vagrant n=ansible | changed: [vmHost2] => (item={'name': 'R5_Nuxez', 'groups': 'G_R5'})
2024-11-21 23:58:33,425 p=4734 u=vagrant n=ansible | changed: [vmHost2] => (item={'name': 'R6_Nuxez', 'groups': 'G_R6'})
2024-11-21 23:58:33,430 p=4734 u=vagrant n=ansible | TASK [Otra tarea] *************************************************************************************************************************************************************************************************************************************************************
2024-11-21 23:58:33,457 p=4734 u=vagrant n=ansible | ok: [vmHost2] => {
    "msg": "Despues de la ejecucion del rol"
}
2024-11-21 23:58:33,462 p=4734 u=vagrant n=ansible | ok: [localhost] => {
    "msg": "Despues de la ejecucion del rol"
}
2024-11-21 23:58:33,471 p=4734 u=vagrant n=ansible | PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
2024-11-21 23:58:33,471 p=4734 u=vagrant n=ansible | localhost                  : ok=4    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-11-21 23:58:33,471 p=4734 u=vagrant n=ansible | vmHost2                    : ok=4    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-11-22 00:18:34,339 p=5439 u=vagrant n=ansible | [WARNING]: While constructing a mapping from /home/vagrant/repogit/TP_AySO_Integral_Nuxez
/ansible/playbook.yml, line 13, column 9, found a duplicate dict key (name). Using last defined value only.

2024-11-22 00:18:34,363 p=5439 u=vagrant n=ansible | PLAY [testing,produccion] *****************************************************************************************************************************************************************************************************************************************************
2024-11-22 00:18:34,372 p=5439 u=vagrant n=ansible | TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
2024-11-22 00:18:35,265 p=5439 u=vagrant n=ansible | ok: [localhost]
2024-11-22 00:18:35,814 p=5439 u=vagrant n=ansible | ok: [vmHost2]
2024-11-22 00:18:35,824 p=5439 u=vagrant n=ansible | TASK [include_role : Alta_Usuarios_Nuxez
] ********************************************************************************************************************************************************************************************************************************
2024-11-22 00:18:35,868 p=5439 u=vagrant n=ansible | TASK [Alta_Usuarios_Nuxez
 : Crear Grupos] ********************************************************************************************************************************************************************************************************************************
2024-11-22 00:18:36,222 p=5439 u=vagrant n=ansible | ok: [localhost] => (item=G_R1)
2024-11-22 00:18:36,388 p=5439 u=vagrant n=ansible | ok: [localhost] => (item=G_R2)
2024-11-22 00:18:36,442 p=5439 u=vagrant n=ansible | ok: [vmHost2] => (item=G_R1)
2024-11-22 00:18:36,582 p=5439 u=vagrant n=ansible | ok: [localhost] => (item=G_R3)
2024-11-22 00:18:36,758 p=5439 u=vagrant n=ansible | ok: [localhost] => (item=G_R4)
2024-11-22 00:18:36,921 p=5439 u=vagrant n=ansible | ok: [vmHost2] => (item=G_R2)
2024-11-22 00:18:36,941 p=5439 u=vagrant n=ansible | ok: [localhost] => (item=G_R5)
2024-11-22 00:18:37,127 p=5439 u=vagrant n=ansible | ok: [localhost] => (item=G_R6)
2024-11-22 00:18:37,362 p=5439 u=vagrant n=ansible | ok: [vmHost2] => (item=G_R3)
2024-11-22 00:18:37,786 p=5439 u=vagrant n=ansible | ok: [vmHost2] => (item=G_R4)
2024-11-22 00:18:38,198 p=5439 u=vagrant n=ansible | ok: [vmHost2] => (item=G_R5)
2024-11-22 00:18:38,600 p=5439 u=vagrant n=ansible | ok: [vmHost2] => (item=G_R6)
2024-11-22 00:18:38,606 p=5439 u=vagrant n=ansible | TASK [Alta_Usuarios_Nuxez
 : Crear usuarios y asignarlos a grupos] ********************************************************************************************************************************************************************************************************
2024-11-22 00:18:39,002 p=5439 u=vagrant n=ansible | ok: [localhost] => (item={'name': 'R1_Nuxez', 'groups': 'G_R1'})
2024-11-22 00:18:39,204 p=5439 u=vagrant n=ansible | changed: [localhost] => (item={'name': 'R2_Nuxez', 'groups': 'G_R2'})
2024-11-22 00:18:39,240 p=5439 u=vagrant n=ansible | ok: [vmHost2] => (item={'name': 'R1_Nuxez', 'groups': 'G_R1'})
2024-11-22 00:18:39,454 p=5439 u=vagrant n=ansible | changed: [localhost] => (item={'name': 'R3_Nuxez', 'groups': 'G_R3'})
2024-11-22 00:18:39,650 p=5439 u=vagrant n=ansible | ok: [localhost] => (item={'name': 'R4_Nuxez', 'groups': 'G_R4'})
2024-11-22 00:18:39,832 p=5439 u=vagrant n=ansible | ok: [localhost] => (item={'name': 'R5_Nuxez', 'groups': 'G_R5'})
2024-11-22 00:18:39,887 p=5439 u=vagrant n=ansible | changed: [vmHost2] => (item={'name': 'R2_Nuxez', 'groups': 'G_R2'})
2024-11-22 00:18:40,065 p=5439 u=vagrant n=ansible | ok: [localhost] => (item={'name': 'R6_Nuxez', 'groups': 'G_R6'})
2024-11-22 00:18:40,449 p=5439 u=vagrant n=ansible | changed: [vmHost2] => (item={'name': 'R3_Nuxez', 'groups': 'G_R3'})
2024-11-22 00:18:40,896 p=5439 u=vagrant n=ansible | ok: [vmHost2] => (item={'name': 'R4_Nuxez', 'groups': 'G_R4'})
2024-11-22 00:18:41,338 p=5439 u=vagrant n=ansible | ok: [vmHost2] => (item={'name': 'R5_Nuxez', 'groups': 'G_R5'})
2024-11-22 00:18:41,774 p=5439 u=vagrant n=ansible | ok: [vmHost2] => (item={'name': 'R6_Nuxez', 'groups': 'G_R6'})
2024-11-22 00:18:41,780 p=5439 u=vagrant n=ansible | TASK [Otra tarea] *************************************************************************************************************************************************************************************************************************************************************
2024-11-22 00:18:41,806 p=5439 u=vagrant n=ansible | ok: [vmHost2] => {
    "msg": "Despues de la ejecucion del rol"
}
2024-11-22 00:18:41,809 p=5439 u=vagrant n=ansible | ok: [localhost] => {
    "msg": "Despues de la ejecucion del rol"
}
2024-11-22 00:18:41,820 p=5439 u=vagrant n=ansible | PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
2024-11-22 00:18:41,820 p=5439 u=vagrant n=ansible | localhost                  : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-11-22 00:18:41,821 p=5439 u=vagrant n=ansible | vmHost2                    : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-11-22 01:08:05,757 p=6100 u=vagrant n=ansible | [WARNING]: While constructing a mapping from /home/vagrant/repogit/TP_AySO_Integral_Nuxez
/ansible/playbook.yml, line 13, column 9, found a duplicate dict key (name). Using last defined value only.

2024-11-22 01:08:05,784 p=6100 u=vagrant n=ansible | PLAY [testing,produccion] *****************************************************************************************************************************************************************************************************************************************************
2024-11-22 01:08:05,792 p=6100 u=vagrant n=ansible | TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
2024-11-22 01:08:06,709 p=6100 u=vagrant n=ansible | ok: [localhost]
2024-11-22 01:08:07,214 p=6100 u=vagrant n=ansible | ok: [vmHost2]
2024-11-22 01:08:07,223 p=6100 u=vagrant n=ansible | TASK [include_role : Sudoers_Grupos] ******************************************************************************************************************************************************************************************************************************************
2024-11-22 01:08:07,264 p=6100 u=vagrant n=ansible | TASK [Sudoers_Grupos : Hacer grupos usar sudo] ********************************************************************************************************************************************************************************************************************************
2024-11-22 01:08:07,314 p=6100 u=vagrant n=ansible | fatal: [vmHost2]: FAILED! => {"msg": "'grupos_sudo' is undefined"}
2024-11-22 01:08:07,315 p=6100 u=vagrant n=ansible | fatal: [localhost]: FAILED! => {"msg": "'grupos_sudo' is undefined"}
2024-11-22 01:08:07,317 p=6100 u=vagrant n=ansible | PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
2024-11-22 01:08:07,317 p=6100 u=vagrant n=ansible | localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-22 01:08:07,317 p=6100 u=vagrant n=ansible | vmHost2                    : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-22 01:08:45,427 p=6230 u=vagrant n=ansible | [WARNING]: While constructing a mapping from /home/vagrant/repogit/TP_AySO_Integral_Nuxez
/ansible/playbook.yml, line 13, column 9, found a duplicate dict key (name). Using last defined value only.

2024-11-22 01:08:45,449 p=6230 u=vagrant n=ansible | PLAY [testing,produccion] *****************************************************************************************************************************************************************************************************************************************************
2024-11-22 01:08:45,457 p=6230 u=vagrant n=ansible | TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
2024-11-22 01:08:46,358 p=6230 u=vagrant n=ansible | ok: [localhost]
2024-11-22 01:08:46,657 p=6230 u=vagrant n=ansible | ok: [vmHost2]
2024-11-22 01:08:46,665 p=6230 u=vagrant n=ansible | TASK [include_role : Sudoers_Grupos] ******************************************************************************************************************************************************************************************************************************************
2024-11-22 01:08:46,704 p=6230 u=vagrant n=ansible | TASK [Sudoers_Grupos : Hacer grupos usar sudo] ********************************************************************************************************************************************************************************************************************************
2024-11-22 01:08:47,154 p=6230 u=vagrant n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/etc/sudoers'
2024-11-22 01:08:47,155 p=6230 u=vagrant n=ansible | failed: [localhost] (item=G_R1) => {"ansible_loop_var": "item", "changed": false, "item": "G_R1", "module_stderr": "Traceback (most recent call last):\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237726.7640903-6336-131386941092829/AnsiballZ_lineinfile.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237726.7640903-6336-131386941092829/AnsiballZ_lineinfile.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237726.7640903-6336-131386941092829/AnsiballZ_lineinfile.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.lineinfile', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_v9iobd0p/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 580, in <module>\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_v9iobd0p/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 570, in main\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_v9iobd0p/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 277, in present\nPermissionError: [Errno 13] Permission denied: b'/etc/sudoers'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
2024-11-22 01:08:47,269 p=6230 u=vagrant n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/etc/sudoers'
2024-11-22 01:08:47,270 p=6230 u=vagrant n=ansible | failed: [vmHost2] (item=G_R1) => {"ansible_loop_var": "item", "changed": false, "item": "G_R1", "module_stderr": "Shared connection to vmhost2 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237726.7932-6335-236226753127854/AnsiballZ_lineinfile.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237726.7932-6335-236226753127854/AnsiballZ_lineinfile.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237726.7932-6335-236226753127854/AnsiballZ_lineinfile.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.lineinfile', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"<frozen runpy>\", line 226, in run_module\r\n  File \"<frozen runpy>\", line 98, in _run_module_code\r\n  File \"<frozen runpy>\", line 88, in _run_code\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_jkcdjcng/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 580, in <module>\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_jkcdjcng/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 570, in main\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_jkcdjcng/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 277, in present\r\nPermissionError: [Errno 13] Permission denied: b'/etc/sudoers'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
2024-11-22 01:08:47,383 p=6230 u=vagrant n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/etc/sudoers'
2024-11-22 01:08:47,384 p=6230 u=vagrant n=ansible | failed: [localhost] (item=G_R2) => {"ansible_loop_var": "item", "changed": false, "item": "G_R2", "module_stderr": "Traceback (most recent call last):\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237727.1599674-6336-1176166425215/AnsiballZ_lineinfile.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237727.1599674-6336-1176166425215/AnsiballZ_lineinfile.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237727.1599674-6336-1176166425215/AnsiballZ_lineinfile.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.lineinfile', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_j2bpep7q/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 580, in <module>\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_j2bpep7q/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 570, in main\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_j2bpep7q/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 277, in present\nPermissionError: [Errno 13] Permission denied: b'/etc/sudoers'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
2024-11-22 01:08:47,603 p=6230 u=vagrant n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/etc/sudoers'
2024-11-22 01:08:47,603 p=6230 u=vagrant n=ansible | failed: [localhost] (item=G_R3) => {"ansible_loop_var": "item", "changed": false, "item": "G_R3", "module_stderr": "Traceback (most recent call last):\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237727.4021924-6336-30829276907356/AnsiballZ_lineinfile.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237727.4021924-6336-30829276907356/AnsiballZ_lineinfile.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237727.4021924-6336-30829276907356/AnsiballZ_lineinfile.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.lineinfile', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_8adiy29u/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 580, in <module>\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_8adiy29u/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 570, in main\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_8adiy29u/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 277, in present\nPermissionError: [Errno 13] Permission denied: b'/etc/sudoers'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
2024-11-22 01:08:47,749 p=6230 u=vagrant n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/etc/sudoers'
2024-11-22 01:08:47,750 p=6230 u=vagrant n=ansible | failed: [vmHost2] (item=G_R2) => {"ansible_loop_var": "item", "changed": false, "item": "G_R2", "module_stderr": "Shared connection to vmhost2 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237727.322883-6335-85446909762535/AnsiballZ_lineinfile.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237727.322883-6335-85446909762535/AnsiballZ_lineinfile.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237727.322883-6335-85446909762535/AnsiballZ_lineinfile.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.lineinfile', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"<frozen runpy>\", line 226, in run_module\r\n  File \"<frozen runpy>\", line 98, in _run_module_code\r\n  File \"<frozen runpy>\", line 88, in _run_code\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_wfkdo00p/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 580, in <module>\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_wfkdo00p/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 570, in main\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_wfkdo00p/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 277, in present\r\nPermissionError: [Errno 13] Permission denied: b'/etc/sudoers'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
2024-11-22 01:08:47,812 p=6230 u=vagrant n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/etc/sudoers'
2024-11-22 01:08:47,813 p=6230 u=vagrant n=ansible | failed: [localhost] (item=G_R4) => {"ansible_loop_var": "item", "changed": false, "item": "G_R4", "module_stderr": "Traceback (most recent call last):\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237727.6080103-6336-196143281693059/AnsiballZ_lineinfile.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237727.6080103-6336-196143281693059/AnsiballZ_lineinfile.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237727.6080103-6336-196143281693059/AnsiballZ_lineinfile.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.lineinfile', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_hzbjx4mf/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 580, in <module>\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_hzbjx4mf/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 570, in main\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_hzbjx4mf/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 277, in present\nPermissionError: [Errno 13] Permission denied: b'/etc/sudoers'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
2024-11-22 01:08:48,051 p=6230 u=vagrant n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/etc/sudoers'
2024-11-22 01:08:48,052 p=6230 u=vagrant n=ansible | failed: [localhost] (item=G_R5) => {"ansible_loop_var": "item", "changed": false, "item": "G_R5", "module_stderr": "Traceback (most recent call last):\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237727.8212943-6336-106237761372300/AnsiballZ_lineinfile.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237727.8212943-6336-106237761372300/AnsiballZ_lineinfile.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237727.8212943-6336-106237761372300/AnsiballZ_lineinfile.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.lineinfile', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_jp3i2woo/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 580, in <module>\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_jp3i2woo/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 570, in main\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_jp3i2woo/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 277, in present\nPermissionError: [Errno 13] Permission denied: b'/etc/sudoers'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
2024-11-22 01:08:48,242 p=6230 u=vagrant n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/etc/sudoers'
2024-11-22 01:08:48,243 p=6230 u=vagrant n=ansible | failed: [localhost] (item=G_R6) => {"ansible_loop_var": "item", "changed": false, "item": "G_R6", "module_stderr": "Traceback (most recent call last):\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237728.0568771-6336-13661333401950/AnsiballZ_lineinfile.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237728.0568771-6336-13661333401950/AnsiballZ_lineinfile.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237728.0568771-6336-13661333401950/AnsiballZ_lineinfile.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.lineinfile', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_ayeh4bn9/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 580, in <module>\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_ayeh4bn9/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 570, in main\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_ayeh4bn9/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 277, in present\nPermissionError: [Errno 13] Permission denied: b'/etc/sudoers'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
2024-11-22 01:08:48,252 p=6230 u=vagrant n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/etc/sudoers'
2024-11-22 01:08:48,252 p=6230 u=vagrant n=ansible | failed: [vmHost2] (item=G_R3) => {"ansible_loop_var": "item", "changed": false, "item": "G_R3", "module_stderr": "Shared connection to vmhost2 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237727.8033538-6335-219930396494445/AnsiballZ_lineinfile.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237727.8033538-6335-219930396494445/AnsiballZ_lineinfile.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237727.8033538-6335-219930396494445/AnsiballZ_lineinfile.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.lineinfile', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"<frozen runpy>\", line 226, in run_module\r\n  File \"<frozen runpy>\", line 98, in _run_module_code\r\n  File \"<frozen runpy>\", line 88, in _run_code\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_m44f717q/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 580, in <module>\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_m44f717q/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 570, in main\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_m44f717q/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 277, in present\r\nPermissionError: [Errno 13] Permission denied: b'/etc/sudoers'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
2024-11-22 01:08:48,659 p=6230 u=vagrant n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/etc/sudoers'
2024-11-22 01:08:48,660 p=6230 u=vagrant n=ansible | failed: [vmHost2] (item=G_R4) => {"ansible_loop_var": "item", "changed": false, "item": "G_R4", "module_stderr": "Shared connection to vmhost2 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237728.3021827-6335-205058173241737/AnsiballZ_lineinfile.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237728.3021827-6335-205058173241737/AnsiballZ_lineinfile.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237728.3021827-6335-205058173241737/AnsiballZ_lineinfile.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.lineinfile', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"<frozen runpy>\", line 226, in run_module\r\n  File \"<frozen runpy>\", line 98, in _run_module_code\r\n  File \"<frozen runpy>\", line 88, in _run_code\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_1ma4we6m/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 580, in <module>\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_1ma4we6m/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 570, in main\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_1ma4we6m/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 277, in present\r\nPermissionError: [Errno 13] Permission denied: b'/etc/sudoers'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
2024-11-22 01:08:49,078 p=6230 u=vagrant n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/etc/sudoers'
2024-11-22 01:08:49,081 p=6230 u=vagrant n=ansible | failed: [vmHost2] (item=G_R5) => {"ansible_loop_var": "item", "changed": false, "item": "G_R5", "module_stderr": "Shared connection to vmhost2 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237728.7147985-6335-269843541523543/AnsiballZ_lineinfile.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237728.7147985-6335-269843541523543/AnsiballZ_lineinfile.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237728.7147985-6335-269843541523543/AnsiballZ_lineinfile.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.lineinfile', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"<frozen runpy>\", line 226, in run_module\r\n  File \"<frozen runpy>\", line 98, in _run_module_code\r\n  File \"<frozen runpy>\", line 88, in _run_code\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_6b67ctkx/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 580, in <module>\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_6b67ctkx/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 570, in main\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_6b67ctkx/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 277, in present\r\nPermissionError: [Errno 13] Permission denied: b'/etc/sudoers'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
2024-11-22 01:08:49,472 p=6230 u=vagrant n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/etc/sudoers'
2024-11-22 01:08:49,473 p=6230 u=vagrant n=ansible | failed: [vmHost2] (item=G_R6) => {"ansible_loop_var": "item", "changed": false, "item": "G_R6", "module_stderr": "Shared connection to vmhost2 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237729.121125-6335-169251491727467/AnsiballZ_lineinfile.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237729.121125-6335-169251491727467/AnsiballZ_lineinfile.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732237729.121125-6335-169251491727467/AnsiballZ_lineinfile.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.lineinfile', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"<frozen runpy>\", line 226, in run_module\r\n  File \"<frozen runpy>\", line 98, in _run_module_code\r\n  File \"<frozen runpy>\", line 88, in _run_code\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_4b242zq6/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 580, in <module>\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_4b242zq6/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 570, in main\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_4b242zq6/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 277, in present\r\nPermissionError: [Errno 13] Permission denied: b'/etc/sudoers'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
2024-11-22 01:08:49,474 p=6230 u=vagrant n=ansible | PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
2024-11-22 01:08:49,474 p=6230 u=vagrant n=ansible | localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-22 01:08:49,474 p=6230 u=vagrant n=ansible | vmHost2                    : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-22 01:19:31,547 p=6800 u=vagrant n=ansible | [WARNING]: While constructing a mapping from /home/vagrant/repogit/TP_AySO_Integral_Nuxez
/ansible/playbook.yml, line 13, column 9, found a duplicate dict key (name). Using last defined value only.

2024-11-22 01:19:31,572 p=6800 u=vagrant n=ansible | PLAY [testing,produccion] *****************************************************************************************************************************************************************************************************************************************************
2024-11-22 01:19:31,580 p=6800 u=vagrant n=ansible | TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
2024-11-22 01:19:32,476 p=6800 u=vagrant n=ansible | ok: [localhost]
2024-11-22 01:19:32,991 p=6800 u=vagrant n=ansible | ok: [vmHost2]
2024-11-22 01:19:33,002 p=6800 u=vagrant n=ansible | TASK [include_role : Sudoers_Grupos] ******************************************************************************************************************************************************************************************************************************************
2024-11-22 01:19:33,045 p=6800 u=vagrant n=ansible | TASK [Sudoers_Grupos : Hacer grupos usar sudo] ********************************************************************************************************************************************************************************************************************************
2024-11-22 01:19:33,417 p=6800 u=vagrant n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/etc/sudoers'
2024-11-22 01:19:33,418 p=6800 u=vagrant n=ansible | failed: [localhost] (item=G_R1) => {"ansible_loop_var": "item", "changed": false, "item": "G_R1", "module_stderr": "Traceback (most recent call last):\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238373.1073027-6909-154949057243990/AnsiballZ_lineinfile.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238373.1073027-6909-154949057243990/AnsiballZ_lineinfile.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238373.1073027-6909-154949057243990/AnsiballZ_lineinfile.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.lineinfile', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_txngd54a/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 580, in <module>\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_txngd54a/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 570, in main\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_txngd54a/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 277, in present\nPermissionError: [Errno 13] Permission denied: b'/etc/sudoers'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
2024-11-22 01:19:33,604 p=6800 u=vagrant n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/etc/sudoers'
2024-11-22 01:19:33,605 p=6800 u=vagrant n=ansible | failed: [vmHost2] (item=G_R1) => {"ansible_loop_var": "item", "changed": false, "item": "G_R1", "module_stderr": "Shared connection to vmhost2 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238373.1388006-6908-101634890290421/AnsiballZ_lineinfile.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238373.1388006-6908-101634890290421/AnsiballZ_lineinfile.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238373.1388006-6908-101634890290421/AnsiballZ_lineinfile.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.lineinfile', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"<frozen runpy>\", line 226, in run_module\r\n  File \"<frozen runpy>\", line 98, in _run_module_code\r\n  File \"<frozen runpy>\", line 88, in _run_code\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_n8fz4p3p/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 580, in <module>\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_n8fz4p3p/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 570, in main\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_n8fz4p3p/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 277, in present\r\nPermissionError: [Errno 13] Permission denied: b'/etc/sudoers'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
2024-11-22 01:19:33,629 p=6800 u=vagrant n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/etc/sudoers'
2024-11-22 01:19:33,629 p=6800 u=vagrant n=ansible | failed: [localhost] (item=G_R2) => {"ansible_loop_var": "item", "changed": false, "item": "G_R2", "module_stderr": "Traceback (most recent call last):\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238373.4232428-6909-237420342525533/AnsiballZ_lineinfile.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238373.4232428-6909-237420342525533/AnsiballZ_lineinfile.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238373.4232428-6909-237420342525533/AnsiballZ_lineinfile.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.lineinfile', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_skl5af2b/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 580, in <module>\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_skl5af2b/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 570, in main\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_skl5af2b/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 277, in present\nPermissionError: [Errno 13] Permission denied: b'/etc/sudoers'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
2024-11-22 01:19:33,855 p=6800 u=vagrant n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/etc/sudoers'
2024-11-22 01:19:33,855 p=6800 u=vagrant n=ansible | failed: [localhost] (item=G_R3) => {"ansible_loop_var": "item", "changed": false, "item": "G_R3", "module_stderr": "Traceback (most recent call last):\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238373.6347654-6909-122343315456823/AnsiballZ_lineinfile.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238373.6347654-6909-122343315456823/AnsiballZ_lineinfile.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238373.6347654-6909-122343315456823/AnsiballZ_lineinfile.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.lineinfile', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_hz83mkxd/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 580, in <module>\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_hz83mkxd/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 570, in main\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_hz83mkxd/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 277, in present\nPermissionError: [Errno 13] Permission denied: b'/etc/sudoers'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
2024-11-22 01:19:34,052 p=6800 u=vagrant n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/etc/sudoers'
2024-11-22 01:19:34,053 p=6800 u=vagrant n=ansible | failed: [localhost] (item=G_R4) => {"ansible_loop_var": "item", "changed": false, "item": "G_R4", "module_stderr": "Traceback (most recent call last):\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238373.8626368-6909-148331441236039/AnsiballZ_lineinfile.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238373.8626368-6909-148331441236039/AnsiballZ_lineinfile.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238373.8626368-6909-148331441236039/AnsiballZ_lineinfile.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.lineinfile', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_44znq0fi/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 580, in <module>\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_44znq0fi/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 570, in main\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_44znq0fi/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 277, in present\nPermissionError: [Errno 13] Permission denied: b'/etc/sudoers'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
2024-11-22 01:19:34,085 p=6800 u=vagrant n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/etc/sudoers'
2024-11-22 01:19:34,086 p=6800 u=vagrant n=ansible | failed: [vmHost2] (item=G_R2) => {"ansible_loop_var": "item", "changed": false, "item": "G_R2", "module_stderr": "Shared connection to vmhost2 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238373.6525028-6908-151699469024605/AnsiballZ_lineinfile.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238373.6525028-6908-151699469024605/AnsiballZ_lineinfile.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238373.6525028-6908-151699469024605/AnsiballZ_lineinfile.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.lineinfile', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"<frozen runpy>\", line 226, in run_module\r\n  File \"<frozen runpy>\", line 98, in _run_module_code\r\n  File \"<frozen runpy>\", line 88, in _run_code\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_xvuflja7/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 580, in <module>\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_xvuflja7/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 570, in main\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_xvuflja7/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 277, in present\r\nPermissionError: [Errno 13] Permission denied: b'/etc/sudoers'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
2024-11-22 01:19:34,282 p=6800 u=vagrant n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/etc/sudoers'
2024-11-22 01:19:34,283 p=6800 u=vagrant n=ansible | failed: [localhost] (item=G_R5) => {"ansible_loop_var": "item", "changed": false, "item": "G_R5", "module_stderr": "Traceback (most recent call last):\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238374.057927-6909-318103777381/AnsiballZ_lineinfile.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238374.057927-6909-318103777381/AnsiballZ_lineinfile.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238374.057927-6909-318103777381/AnsiballZ_lineinfile.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.lineinfile', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_xk1g5y94/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 580, in <module>\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_xk1g5y94/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 570, in main\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_xk1g5y94/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 277, in present\nPermissionError: [Errno 13] Permission denied: b'/etc/sudoers'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
2024-11-22 01:19:34,468 p=6800 u=vagrant n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/etc/sudoers'
2024-11-22 01:19:34,468 p=6800 u=vagrant n=ansible | failed: [localhost] (item=G_R6) => {"ansible_loop_var": "item", "changed": false, "item": "G_R6", "module_stderr": "Traceback (most recent call last):\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238374.288802-6909-24674691368338/AnsiballZ_lineinfile.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238374.288802-6909-24674691368338/AnsiballZ_lineinfile.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238374.288802-6909-24674691368338/AnsiballZ_lineinfile.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.lineinfile', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_8vyzanzx/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 580, in <module>\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_8vyzanzx/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 570, in main\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_8vyzanzx/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 277, in present\nPermissionError: [Errno 13] Permission denied: b'/etc/sudoers'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
2024-11-22 01:19:34,560 p=6800 u=vagrant n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/etc/sudoers'
2024-11-22 01:19:34,560 p=6800 u=vagrant n=ansible | failed: [vmHost2] (item=G_R3) => {"ansible_loop_var": "item", "changed": false, "item": "G_R3", "module_stderr": "Shared connection to vmhost2 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238374.1369326-6908-127451248816010/AnsiballZ_lineinfile.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238374.1369326-6908-127451248816010/AnsiballZ_lineinfile.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238374.1369326-6908-127451248816010/AnsiballZ_lineinfile.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.lineinfile', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"<frozen runpy>\", line 226, in run_module\r\n  File \"<frozen runpy>\", line 98, in _run_module_code\r\n  File \"<frozen runpy>\", line 88, in _run_code\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_9w7qvtve/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 580, in <module>\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_9w7qvtve/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 570, in main\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_9w7qvtve/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 277, in present\r\nPermissionError: [Errno 13] Permission denied: b'/etc/sudoers'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
2024-11-22 01:19:34,960 p=6800 u=vagrant n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/etc/sudoers'
2024-11-22 01:19:34,960 p=6800 u=vagrant n=ansible | failed: [vmHost2] (item=G_R4) => {"ansible_loop_var": "item", "changed": false, "item": "G_R4", "module_stderr": "Shared connection to vmhost2 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238374.6029122-6908-226663238193151/AnsiballZ_lineinfile.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238374.6029122-6908-226663238193151/AnsiballZ_lineinfile.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238374.6029122-6908-226663238193151/AnsiballZ_lineinfile.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.lineinfile', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"<frozen runpy>\", line 226, in run_module\r\n  File \"<frozen runpy>\", line 98, in _run_module_code\r\n  File \"<frozen runpy>\", line 88, in _run_code\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_g5j2r9ua/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 580, in <module>\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_g5j2r9ua/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 570, in main\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_g5j2r9ua/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 277, in present\r\nPermissionError: [Errno 13] Permission denied: b'/etc/sudoers'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
2024-11-22 01:19:35,356 p=6800 u=vagrant n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/etc/sudoers'
2024-11-22 01:19:35,357 p=6800 u=vagrant n=ansible | failed: [vmHost2] (item=G_R5) => {"ansible_loop_var": "item", "changed": false, "item": "G_R5", "module_stderr": "Shared connection to vmhost2 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238375.0010386-6908-209088744215456/AnsiballZ_lineinfile.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238375.0010386-6908-209088744215456/AnsiballZ_lineinfile.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238375.0010386-6908-209088744215456/AnsiballZ_lineinfile.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.lineinfile', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"<frozen runpy>\", line 226, in run_module\r\n  File \"<frozen runpy>\", line 98, in _run_module_code\r\n  File \"<frozen runpy>\", line 88, in _run_code\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_ohso_ai9/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 580, in <module>\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_ohso_ai9/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 570, in main\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_ohso_ai9/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 277, in present\r\nPermissionError: [Errno 13] Permission denied: b'/etc/sudoers'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
2024-11-22 01:19:35,761 p=6800 u=vagrant n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 13] Permission denied: b'/etc/sudoers'
2024-11-22 01:19:35,763 p=6800 u=vagrant n=ansible | failed: [vmHost2] (item=G_R6) => {"ansible_loop_var": "item", "changed": false, "item": "G_R6", "module_stderr": "Shared connection to vmhost2 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238375.396818-6908-139570287244738/AnsiballZ_lineinfile.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238375.396818-6908-139570287244738/AnsiballZ_lineinfile.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1732238375.396818-6908-139570287244738/AnsiballZ_lineinfile.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.lineinfile', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"<frozen runpy>\", line 226, in run_module\r\n  File \"<frozen runpy>\", line 98, in _run_module_code\r\n  File \"<frozen runpy>\", line 88, in _run_code\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_km146cdm/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 580, in <module>\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_km146cdm/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 570, in main\r\n  File \"/tmp/ansible_ansible.builtin.lineinfile_payload_km146cdm/ansible_ansible.builtin.lineinfile_payload.zip/ansible/modules/lineinfile.py\", line 277, in present\r\nPermissionError: [Errno 13] Permission denied: b'/etc/sudoers'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
2024-11-22 01:19:35,764 p=6800 u=vagrant n=ansible | PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
2024-11-22 01:19:35,765 p=6800 u=vagrant n=ansible | localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-22 01:19:35,765 p=6800 u=vagrant n=ansible | vmHost2                    : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-22 01:20:28,435 p=7113 u=vagrant n=ansible | [WARNING]: While constructing a mapping from /home/vagrant/repogit/TP_AySO_Integral_Nuxez
/ansible/playbook.yml, line 13, column 9, found a duplicate dict key (name). Using last defined value only.

2024-11-22 01:20:28,459 p=7113 u=vagrant n=ansible | PLAY [testing,produccion] *****************************************************************************************************************************************************************************************************************************************************
2024-11-22 01:20:28,466 p=7113 u=vagrant n=ansible | TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
2024-11-22 01:20:29,396 p=7113 u=vagrant n=ansible | ok: [localhost]
2024-11-22 01:20:29,716 p=7113 u=vagrant n=ansible | ok: [vmHost2]
2024-11-22 01:20:29,725 p=7113 u=vagrant n=ansible | TASK [include_role : Sudoers_Grupos] ******************************************************************************************************************************************************************************************************************************************
2024-11-22 01:20:29,768 p=7113 u=vagrant n=ansible | TASK [Sudoers_Grupos : Hacer grupos usar sudo] ********************************************************************************************************************************************************************************************************************************
2024-11-22 01:20:30,132 p=7113 u=vagrant n=ansible | changed: [localhost] => (item=G_R1)
2024-11-22 01:20:30,296 p=7113 u=vagrant n=ansible | changed: [localhost] => (item=G_R2)
2024-11-22 01:20:30,365 p=7113 u=vagrant n=ansible | changed: [vmHost2] => (item=G_R1)
2024-11-22 01:20:30,508 p=7113 u=vagrant n=ansible | changed: [localhost] => (item=G_R3)
2024-11-22 01:20:30,695 p=7113 u=vagrant n=ansible | changed: [localhost] => (item=G_R4)
2024-11-22 01:20:30,865 p=7113 u=vagrant n=ansible | changed: [vmHost2] => (item=G_R2)
2024-11-22 01:20:30,884 p=7113 u=vagrant n=ansible | changed: [localhost] => (item=G_R5)
2024-11-22 01:20:31,093 p=7113 u=vagrant n=ansible | changed: [localhost] => (item=G_R6)
2024-11-22 01:20:31,337 p=7113 u=vagrant n=ansible | changed: [vmHost2] => (item=G_R3)
2024-11-22 01:20:31,754 p=7113 u=vagrant n=ansible | changed: [vmHost2] => (item=G_R4)
2024-11-22 01:20:32,178 p=7113 u=vagrant n=ansible | changed: [vmHost2] => (item=G_R5)
2024-11-22 01:20:32,599 p=7113 u=vagrant n=ansible | changed: [vmHost2] => (item=G_R6)
2024-11-22 01:20:32,604 p=7113 u=vagrant n=ansible | TASK [Otra tarea] *************************************************************************************************************************************************************************************************************************************************************
2024-11-22 01:20:32,630 p=7113 u=vagrant n=ansible | ok: [vmHost2] => {
    "msg": "Despues de la ejecucion del rol"
}
2024-11-22 01:20:32,633 p=7113 u=vagrant n=ansible | ok: [localhost] => {
    "msg": "Despues de la ejecucion del rol"
}
2024-11-22 01:20:32,644 p=7113 u=vagrant n=ansible | PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
2024-11-22 01:20:32,645 p=7113 u=vagrant n=ansible | localhost                  : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-11-22 01:20:32,646 p=7113 u=vagrant n=ansible | vmHost2                    : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-11-23 01:08:21,071 p=1946 u=vagrant n=ansible | [WARNING]: While constructing a mapping from /home/vagrant/repogit/TP_AySO_Integral_Nuxez
/ansible/playbook.yml, line 13, column 9, found a duplicate dict key (name). Using last defined value only.

2024-11-23 01:08:21,171 p=1946 u=vagrant n=ansible | PLAY [testing,produccion] *****************************************************************************************************************************************************************************************************************************************************
2024-11-23 01:08:21,204 p=1946 u=vagrant n=ansible | TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
2024-11-23 01:08:23,020 p=1946 u=vagrant n=ansible | ok: [localhost]
2024-11-23 01:08:24,622 p=1946 u=vagrant n=ansible | ok: [vmHost2]
2024-11-23 01:08:24,632 p=1946 u=vagrant n=ansible | TASK [include_role : Instalar-tools_Nuxez
] *******************************************************************************************************************************************************************************************************************************
2024-11-23 01:08:24,702 p=1946 u=vagrant n=ansible | TASK [Instalar-tools_Nuxez
 : Instalar programas] *************************************************************************************************************************************************************************************************************************
2024-11-23 01:08:25,972 p=1946 u=vagrant n=ansible | failed: [vmHost2] (item=htop) => {"ansible_loop_var": "item", "changed": false, "item": "htop", "msg": "This command has to be run under the root user.", "results": []}
2024-11-23 01:08:26,838 p=1946 u=vagrant n=ansible | failed: [vmHost2] (item=tmux) => {"ansible_loop_var": "item", "changed": false, "item": "tmux", "msg": "This command has to be run under the root user.", "results": []}
2024-11-23 01:08:27,563 p=1946 u=vagrant n=ansible | failed: [localhost] (item=htop) => {"ansible_loop_var": "item", "changed": false, "item": "htop", "msg": "'/usr/bin/apt-mark manual htop' failed: E: Could not create temporary file for /var/lib/apt/extended_states - mkstemp (13: Permission denied)\nE: Failed to write temporary StateFile /var/lib/apt/extended_states\n", "rc": 100, "stderr": "E: Could not create temporary file for /var/lib/apt/extended_states - mkstemp (13: Permission denied)\nE: Failed to write temporary StateFile /var/lib/apt/extended_states\n", "stderr_lines": ["E: Could not create temporary file for /var/lib/apt/extended_states - mkstemp (13: Permission denied)", "E: Failed to write temporary StateFile /var/lib/apt/extended_states"], "stdout": "", "stdout_lines": []}
2024-11-23 01:08:27,716 p=1946 u=vagrant n=ansible | failed: [vmHost2] (item=speedtest-cli) => {"ansible_loop_var": "item", "changed": false, "item": "speedtest-cli", "msg": "This command has to be run under the root user.", "results": []}
2024-11-23 01:08:28,341 p=1946 u=vagrant n=ansible | failed: [localhost] (item=tmux) => {"ansible_loop_var": "item", "changed": false, "item": "tmux", "msg": "'/usr/bin/apt-mark manual tmux' failed: E: Could not create temporary file for /var/lib/apt/extended_states - mkstemp (13: Permission denied)\nE: Failed to write temporary StateFile /var/lib/apt/extended_states\n", "rc": 100, "stderr": "E: Could not create temporary file for /var/lib/apt/extended_states - mkstemp (13: Permission denied)\nE: Failed to write temporary StateFile /var/lib/apt/extended_states\n", "stderr_lines": ["E: Could not create temporary file for /var/lib/apt/extended_states - mkstemp (13: Permission denied)", "E: Failed to write temporary StateFile /var/lib/apt/extended_states"], "stdout": "", "stdout_lines": []}
2024-11-23 01:08:29,109 p=1946 u=vagrant n=ansible | failed: [localhost] (item=speedtest-cli) => {"ansible_loop_var": "item", "cache_update_time": 1732152529, "cache_updated": false, "changed": false, "item": "speedtest-cli", "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"      install 'speedtest-cli'' failed: E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)\nE: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?\n", "rc": 100, "stderr": "E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)\nE: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?\n", "stderr_lines": ["E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)", "E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?"], "stdout": "", "stdout_lines": []}
2024-11-23 01:08:29,114 p=1946 u=vagrant n=ansible | PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
2024-11-23 01:08:29,114 p=1946 u=vagrant n=ansible | localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-23 01:08:29,115 p=1946 u=vagrant n=ansible | vmHost2                    : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-23 01:10:54,852 p=2187 u=vagrant n=ansible | [WARNING]: While constructing a mapping from /home/vagrant/repogit/TP_AySO_Integral_Nuxez
/ansible/playbook.yml, line 13, column 9, found a duplicate dict key (name). Using last defined value only.

2024-11-23 01:10:54,876 p=2187 u=vagrant n=ansible | PLAY [testing,produccion] *****************************************************************************************************************************************************************************************************************************************************
2024-11-23 01:10:54,885 p=2187 u=vagrant n=ansible | TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
2024-11-23 01:10:55,772 p=2187 u=vagrant n=ansible | ok: [localhost]
2024-11-23 01:10:56,304 p=2187 u=vagrant n=ansible | ok: [vmHost2]
2024-11-23 01:10:56,313 p=2187 u=vagrant n=ansible | TASK [include_role : Instalar-tools_Nuxez
] *******************************************************************************************************************************************************************************************************************************
2024-11-23 01:10:56,352 p=2187 u=vagrant n=ansible | TASK [Instalar-tools_Nuxez
 : Instalar programas] *************************************************************************************************************************************************************************************************************************
2024-11-23 01:10:57,465 p=2187 u=vagrant n=ansible | ok: [localhost] => (item=htop)
2024-11-23 01:10:58,237 p=2187 u=vagrant n=ansible | ok: [localhost] => (item=tmux)
2024-11-23 01:11:13,289 p=2187 u=vagrant n=ansible | changed: [vmHost2] => (item=htop)
2024-11-23 01:11:19,406 p=2187 u=vagrant n=ansible | changed: [localhost] => (item=speedtest-cli)
2024-11-23 01:11:26,465 p=2187 u=vagrant n=ansible | changed: [vmHost2] => (item=tmux)
2024-11-23 01:11:38,455 p=2187 u=vagrant n=ansible | changed: [vmHost2] => (item=speedtest-cli)
2024-11-23 01:11:38,509 p=2187 u=vagrant n=ansible | TASK [Otra tarea] *************************************************************************************************************************************************************************************************************************************************************
2024-11-23 01:11:38,538 p=2187 u=vagrant n=ansible | ok: [vmHost2] => {
    "msg": "Despues de la ejecucion del rol"
}
2024-11-23 01:11:38,543 p=2187 u=vagrant n=ansible | ok: [localhost] => {
    "msg": "Despues de la ejecucion del rol"
}
2024-11-23 01:11:38,553 p=2187 u=vagrant n=ansible | PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
2024-11-23 01:11:38,553 p=2187 u=vagrant n=ansible | localhost                  : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-11-23 01:11:38,553 p=2187 u=vagrant n=ansible | vmHost2                    : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
